config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get "/about"=>"public/homes#about",as: 'about'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    get '/customers/my_page', to: 'customers#show'
    get '/customers/information/edit', to: 'customers#edit'
    get '/customers/check', to: 'customers#check'
    patch '/customers/withdraw', to: 'customers#withdraw'
    patch '/customers/information', to: 'customers#update'
    resources :items, only: [:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm'
        get 'success', to: 'orders#success'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
}

  get '/admin', to: 'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  validates :amount, presence: true
  
  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_many :cart_items

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, uniqueness: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
  def add_tax_price
    (self.price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: {
    awaiting_payment: 0,
    payment_confirmed: 1,
    in_production: 2,
    preparing_for_shipping: 3,
    shipped: 4
  }
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: {
    not_available: 0,
    waiting: 1,
    in_progress: 2,
    completed: 3
  }
  
  validates :price, presence: true
  validates :amount, presence: true
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
     @orders = Order.includes(:customer, :order_details).order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end

def create
    @item = Item.new(item_params)
    if @item.save
        flash[:notice] = 'You have created item successfully'
        redirect_to admin_item_path(@item) # ここでadmin_item_pathを使用します
    else
        render :new
    end
end

  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[notice] = 'You have updated item successfully'
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_active, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
  end
  
  
  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      flash[:notice] = "注文ステータスの更新に成功しました"
      redirect_to admin_order_path(@order)
    else
      flash[:alert] = "注文ステータスの更新に失敗しました"
      render :show
    end
  end
  
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      customers_my_page_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      admin_path
    elsif resource_or_scope == :customer
      root_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/unlocks_controller.rb
# frozen_string_literal: true

class Public::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>

<p><strong>購入者</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "#{@order.customer.last_name} #{@order.customer.first_name}", admin_customer_path(@order.customer), class: "name-link" %></p>

<p><strong>注文日</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @order.created_at.strftime("%Y/%m/%d") %></p>

<p><strong>配送先</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;〒<%= @order.post_code %><%= @order.address %><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @order.name %></p>


<p><strong>支払方法</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @order.payment_method_i18n %></p>

<div class="status-container">
    <p><strong>注文ステータス</strong></p>
    <div class="status-form">
        <%= form_with model: @order, url: admin_order_path(@order), local: true, method: :patch do |f| %>
            <%= f.select :status, Order.statuses_i18n.keys.map { |status| [Order.statuses_i18n[status], status] }, selected: @order.status %>
            <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
    </div>
</div>

<style>
table {
    padding: 0;
    width: 16cm;
    height: 1cm;
    border-collapse: separate;
    border-spacing: 0;
    border-top: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
}
th, td {
    padding: 8px;
    text-align: left;
}

th {
    background-color: #f2f2f2;
}

table td a {
    text-decoration: underline;
    color: black;
}

h2 {
    background-color: #f5f5f5;
    text-align: center;
    padding: 0;
    width: 8cm;
    height: 1cm;
}

p2 {
    position: absolute;
    top: 64%;
    right: 0;
    left: 70%;
}

.btn.btn-success {
    font-weight: bold;
    font-size: 15px;
    margin: 10px;
    margin-top: 0px;
}

form select {
    width: 4.5cm;
    height: 1cm;
    text-align: center;
    font-size: 20px;
    border-radius: 5px;
}

.status-container {
    display: flex; 
    align-items: center;
}

.status-form {
    margin-left: 10px;
}

body {
    width: 80%;
    margin: 0 auto;
}

.name-link {
    color: #000000;
    text-decoration: underline;
}
</style>

<table class="table-half">
  <thead>
    <tr>
      <th>商品名</th>
      <th>単価 (税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th>制作ステータス</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @order.order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= number_to_currency(order_detail.price, unit: "円") %></td>
        <td><%= order_detail.amount %></td>
        <td><%= number_to_currency(order_detail.price * order_detail.amount, unit: "円") %></td>
        <td>
          <%= form_with model: order_detail, url:admin_order_detail_path(order_detail.id), method: :patch do |f| %>
            <%= f.select :making_status, [
              [OrderDetail.making_statuses_i18n[:not_available], :not_available],
              [OrderDetail.making_statuses_i18n[:waiting], :waiting],
              [OrderDetail.making_statuses_i18n[:in_progress], :in_progress],
              [OrderDetail.making_statuses_i18n[:completed], :completed]
            ] %>
          <%= f.submit "更新", class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<p2>
<strong>商品合計:</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= number_to_currency(@order.order_details.sum { |order_detail| order_detail.price * order_detail.amount }, unit: "円") %>
<br><strong>送料:</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= number_to_currency(@order.shipping_cost, unit: "円") %>
<br><strong>請求合計金額:</strong> &nbsp;&nbsp;&nbsp;&nbsp;<strong><%= number_to_currency(@order.total_payment, unit: "円") %></strong>
</p2>