config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get "/about"=>"public/homes#about",as: 'about'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    get '/customers/my_page', to: 'customers#show'
    get '/customers/information/edit', to: 'customers#edit'
    get '/customers/check', to: 'customers#check'
    patch '/customers/withdraw', to: 'customers#withdraw'
    patch '/customers/information', to: 'customers#update'
    resources :items, only: [:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm'
        get 'success', to: 'orders#success'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
}

  get '/admin', to: 'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  validates :amount, presence: true
  
  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_many :cart_items

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, uniqueness: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
  def add_tax_price
    (self.price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: {
    awaiting_payment: 0,
    payment_confirmed: 1,
    in_production: 2,
    preparing_for_shipping: 3,
    shipped: 4
  }
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: {
    not_available: 0,
    waiting: 1,
    in_progress: 2,
    completed: 3
  }
  
  validates :price, presence: true
  validates :amount, presence: true
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    end
  end
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
     @orders = Order.includes(:customer, :order_details).order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end

def create
    @item = Item.new(item_params)
    if @item.save
        flash[:notice] = 'You have created item successfully'
        redirect_to admin_item_path(@item) # ここでadmin_item_pathを使用します
    else
        render :new
    end
end

  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[notice] = 'You have updated item successfully'
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      customers_my_page_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      admin_path
    elsif resource_or_scope == :customer
      root_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/unlocks_controller.rb
# frozen_string_literal: true

class Public::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>
<br></br>
<style>
table {
    padding: 0;
    width: 8cm;
    height: 1cm;
    border-collapse: separate;
    border-spacing: 0;
    border-top: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ccc;
}

th {
    background-color: #f2f2f2;
}

table td a {
    text-decoration: underline;
    color: black;
}

h2 {
    background-color: #f5f5f5;
    text-align: center;
    padding: 0;
    width: 6cm;
    height: 1cm;
}

.btn.btn-success {
    font-weight: bold;
    width: 3.5cm;
    height: 1cm;
    border-radius: 10px;
}

.form-group {
    display: flex;
    align-items: center;
    gap: 10px;
}

.form-group label {
    margin-right: 10px;
}

body {
    width: 80%;
    margin: 0 auto;
}
</style>

<%= form_with model: @genre, url: admin_genre_path do |f| %>
    <div class="form-group">
        <%= f.label :name, 'ジャンル名' %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.text_field :name %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.submit '変更を保存', class: 'btn btn-success' %>
    </div>
<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>
<br></br
<%= form_with model: @genre, url: admin_genres_path do |f| %>

  <div class="form-group">
    &nbsp;&nbsp;&nbsp;<%= f.label :name, 'ジャンル名' %>
    &nbsp;&nbsp;&nbsp;&nbsp;<%= f.text_field :name, placeholder: "ジャンル名" %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.submit '新規登録', class: "btn btn-default" %>
  </div>
<% end %>

<style>
table {
    padding: 0;
    width: 8cm;
    height: 1cm;
    border-collapse: separate;
    border-spacing: 0;
    border-top: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ccc;
}

th {
    background-color: #f2f2f2;
}

table td a {
    text-decoration: underline;
    color: black;
}

h2 {
    background-color: #f5f5f5;
    text-align: center;
    padding: 0;
    width: 8cm;
    height: 1cm;
}

.btn.btn-success {
    font-weight: bold;
    font-size: 15px;
    margin: 10px;
    margin-top: 0px;
    text-decoration: none;
    float: right /* これ使いやすいよ！ */
}

.btn.btn-default {
    background-color: #28a745;
    color: #fff;
    font-weight: bold;
    width: 3.5cm;
    height: 1cm;
    border-radius: 10px;
}

body {
    width: 80%;
    margin: 0 auto;
}
</style>

<table class="table-half">
  <thead>
    <tr>
      <th>ジャンル</th>
    </tr>
  </thead>
  <tbody>
    <% @genres.each do |genre| %>
    <tr>
     <td>
      <%= genre.name %> <%= raw "&nbsp;" %> <%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %>
     </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>

<style>
table {
    width: 12cm;
    height: 1cm;
    border-spacing: 0;
    position: absolute;
    top: 20%;
    right: 43%;
    left: 38%;
    font-size: 18px;
}

th, td {
    padding: 20px;
    text-align: left;
}



table td a {
    text-decoration: underline;
    color: black;
}

h2 {
    background-color: #f5f5f5;
    text-align: center;
    padding: 0;
    width: 5cm;
    height: 1;
}

.btn.btn-success {
    background-color: #28a745;
    color: #fff;
    font-weight: bold;
    width: 3.5cm;
    height: 1cm;
    border-radius: 10px;
    text-decoration: none;
    position: relative;
    right: 0%;
    left: 100%;
}

body {
    width: 80%;
    margin: 0 auto;
}
</style>

<%= form_with model: @item, url: admin_item_path do |f| %>
<table>

  <tr>
    <td><%= f.label :image, '商品画像', for: 'item_image' %></td>
    <td><%= f.file_field :image, id: 'item_image' %></td>
  </tr>
  <tr>
    <td><%= f.label :name, '商品名' %></td>
    <td><%= f.text_field :name, class: "form-control name" %></td>
  </tr>
  <tr>
    <td><%= f.label :introduction, '商品説明' %></td>
    <td><%= f.text_area :introduction, class: "form-control introduction" %></td>
  </tr>
  <tr>
    <td><%= f.label :genre_id, 'ジャンル' %></td>
    <td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: 'Select Genre', class: "form-control genre-select" %></td>
  </tr>
  <tr>
    <td><%= f.label :price, '税抜価格' %></td>
    <td><%= f.text_field :price, class: "form-control introduction" %>円</td>
  </tr>
  <tr>
    <td><%= f.label :is_active, '販売ステータス' %></td>
    <td>
      <%= f.radio_button :is_active, true %> 販売中
      <%= f.radio_button :is_active, false %> 販売停止中
    </td>
  </tr>
  <tr>
    <td><%= f.submit '変更を保存', class: 'btn btn-success' %></td>
  </tr>
</table>
<% end %>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>
<br></br>
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>

table {
    width: 100%;
    border-collapse: separate;
    border-spacing: 0;
    border-top: 1px solid #ccc;
    border-bottom: 1px solid #ccc;
}
th, td {
    padding: 8px;
    text-align: left;
}
th {
    background-color: #f2f2f2;
}

table td a {
    text-decoration: underline;
    color: black;
}

h2 {
    background-color: #f5f5f5;
    text-align: center;
    padding: 0;
    width: 5cm;
    height: 1cm;
}

.btn.btn-default{
  width: 55px;
  height: 55px;
  border-radius: 50%;
  transition: .2s;
  box-shadow: 2px 2px #666666;
  font-size: 25px;
  background-color: white;
  color: #666666;
  border: white;
  position: absolute;
  top: 8%;
  right: 30;
  left: 80%;
}

body {
    width: 80%;
    margin: 0 auto;
}

.status-active {
    color: #28a745;
    font-weight: bold;
}

.status-inactive {
    color: #ccc;
    font-weight: bold;
}
</style>
</head>
<body>
<div>
  <%= link_to '＋', new_admin_item_path, class: 'btn btn-default' %>
</div>

<table>
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item) %></td>
      <td><%= item.price.to_s(:delimited) %></td>
      <td><%= item.genre.name %></td>
      <td class="<%= item.is_active ? 'status-active' : 'status-inactive' %>">
        <%= item.is_active ? '販売中' : '販売停止中' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @items %>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>

<style>
table {
    width: 12cm;
    height: 1cm;
    border-spacing: 0;
    position: absolute;
    top: 20%;
    right: 43%;
    left: 38%;
    font-size: 18px;
}

th, td {
    padding: 20px;
    text-align: left;
}

th {
    background-color: #f2f2f2;
}

table td a {
    text-decoration: underline;
    color: black;
}

h2 {
    background-color: #f5f5f5;
    text-align: center;
    width: 6cm;
    height: 1cm;
}

.btn.btn-success {
    background-color: #28a745;
    color: #fff;
    font-weight: bold;
    width: 3.5cm;
    height: 1cm;
    border-radius: 10px;
    text-decoration: none;
    position: relative;
    right: 0%;
    left: 100%;
}

body {
    width: 80%;
    margin: 0 auto;
}
</style>

<%= form_with model: @item, url: admin_items_path do |f| %>
<table>
  
  <tr>
    <td><%= f.label :image, '商品画像', for: 'item_image' %></td>
    <td><%= f.file_field :image, id: 'item_image' %></td>
  </tr>
  <tr>
    <td><%= f.label :name, '商品名' %></td>
    <td><%= f.text_field :name, placeholder: "商品名", class: "form-control name" %></td>
  </tr>
  <tr>
    <td><%= f.label :introduction, '商品説明' %></td>
    <td><%= f.text_area :introduction, placeholder: 'ここに説明文を記述します', class: "form-control introduction" %></td>
  </tr>
  <tr>
    <td><%= f.label :genre_id, 'ジャンル' %></td>
    <td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: '選択してください', class: "form-control genre-select" %></td>
  </tr>
  <tr>
    <td><%= f.label :price, '税抜価格' %></td>
    <td><%= f.text_field :price, placeholder: '1000', class: "form-control introduction" %></td>
    <td>円</td>
  </tr>
  <tr>
    <td><%= f.label :is_active, '販売ステータス' %></td>
    <td>
      <%= f.radio_button :is_active, true %> 販売中
      <%= f.radio_button :is_active, false %> 販売停止中
    </td>
  </tr>
  <tr>
    <td><%= f.submit '新規登録', class: 'btn btn-success' %></td>
  </tr>

</table>
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>

<style>
table {
    padding: 0;
    width: 12cm;
    height: 1cm;
    border-collapse: separate;
    border-spacing: 0;
    position: absolute;
    top: 25%;
    right: 35;
    left: 40%;
    font-size: 20px;
}

th, td {
    padding: 20px;
    text-align: left;
}

th {
    background-color: #f2f2f2;
}

table td a {
    text-decoration: underline;
    color: black;
}

h2 {
    background-color: #f5f5f5;
    text-align: center;
    padding: 0;
    width: 5cm;
    height: 1cm;
}

.btn.btn-success {
    background-color: #28a745;
    color: #fff;
    font-weight: bold;
    width: 3.5cm;
    height: 1cm;
    border-radius: 10px;
    text-decoration: none;
}

.container {
    display: flex;
    flex-direction: row;
    justify-content: left;
}

.status-active {
    color: #28a745;
    font-weight: bold;
}

.status-inactive {
    color: #ccc;
    font-weight: bold;
}

body {
    width: 80%;
    margin: 0 auto;
}
</style>

<div class="container">
  <%= image_tag @item.image, size: '200x200', alt: @item.name if @item.image.attached? %>
</div>

<table>
  <tr>
    <td>商品名</td>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <td>商品説明</td>
    <td><%= @item.introduction %></td>
  </tr>
  <tr>
    <td>ジャンル</td>
    <td><%= @item.genre.name %></td>
  </tr>
  <tr>
    <td>税込価格<br>(税抜価格)</td>
    <td><%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>) 円</td>
  </tr>
  <tr>
    <td>販売ステータス</td>
    <td class="<%= @item.is_active ? 'status-active' : 'status-inactive' %>">
      <% if @item.is_active %>
        販売中
      <% else %>
        販売停止中
      <% end %>
    </td>
  </tr>
  <tr>
    <td><%= link_to '編集する', edit_admin_item_path(@item), class: 'btn btn-success' %></td>
  </tr>
</table>