config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'
  get "/about"=>"public/homes#about",as: 'about'
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    get '/customers/my_page', to: 'customers#show'
    get '/customers/information/edit', to: 'customers#edit'
    get '/customers/check', to: 'customers#check'
    patch '/customers/withdraw', to: 'customers#withdraw'
    patch '/customers/information', to: 'customers#update'
    resources :items, only: [:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all', to: 'cart_items#destroy_all'
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm', to: 'orders#confirm'
        get 'success', to: 'orders#success'
      end
    end
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
}

  get '/admin', to: 'admin/homes#top'
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  validates :amount, presence: true
  
  def subtotal
    item.add_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :addresses
  has_many :cart_items

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, uniqueness: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  
  has_one_attached :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  
  def add_tax_price
    (self.price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  
  enum status: {
    awaiting_payment: 0,
    payment_confirmed: 1,
    in_production: 2,
    preparing_for_shipping: 3,
    shipped: 4
  }
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  validates :shipping_cost, presence: true
  validates :total_payment, presence: true
  validates :payment_method, presence: true
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: {
    not_available: 0,
    waiting: 1,
    in_progress: 2,
    completed: 3
  }
  
  validates :price, presence: true
  validates :amount, presence: true
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
     @orders = Order.includes(:customer, :order_details).order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when Customer
      customers_my_page_path
    else
      root_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      admin_path
    elsif resource_or_scope == :customer
      root_path
    else
      root_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/unlocks_controller.rb
# frozen_string_literal: true

class Public::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkGithub</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/f61b6e8d11.js" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
    .menu li:first-child a {
      font-weight: bold;
      color: black;
      font-size: 2rem;
      display: block;
      margin-bottom: 10px;
      position: relative;
      top: 10%;
      right: 150%;
      left: -400%;
    }
  </style>
</head>
<body>
  <% if customer_signed_in? %>
    <p style="position: absolute; top: 5%; left: 41%;">ようこそ、<%= current_customer.last_name %>さん！</p>
    <ul class="menu">
      <li><%= link_to 'Nagano Cake', root_path %></li>
      <li><%= link_to '商品一覧', items_path, class: 'menu-button' %></li>
      <li><%= link_to 'マイページ', customers_my_page_path, class: 'menu-button' %></li>
      <li><%= link_to 'カート', cart_items_path, class: 'menu-button' %></li>
      <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'menu-button' %></li>
    </ul>
  <% elsif admin_signed_in? && !customer_signed_in? %>
    <ul class="menu">
      <li><%= link_to 'Nagano Cake', admin_path %></li>
      <li><%= link_to '商品一覧', admin_items_path, class: 'menu-button' %></li>
      <li><%= link_to '会員一覧', admin_customers_path, class: 'menu-button' %></li>
      <li><%= link_to '注文履歴一覧', admin_path, class: 'menu-button' %></li>
      <li><%= link_to 'ジャンル一覧', admin_genres_path, class: 'menu-button' %></li>
      <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'menu-button' %></li>
    </ul>
  <% else %>
    <ul class="menu">
      <li><%= link_to 'Nagano Cake', root_path %></li>
      <li><%= link_to 'About', about_path, class: 'menu-button' %></li>
      <li><%= link_to '商品一覧', items_path, class: 'menu-button' %></li>
      <li><%= link_to '新規登録', new_customer_registration_path, class: 'menu-button' %></li>
      <li><%= link_to 'ログイン', new_customer_session_path, class: 'menu-button' %></li>
    </ul>
  <% end %>
  <%= yield %>
</body>
</html>